---
output:
  pdf_document: default
  html_document: default
---
# Introducción {-}

Son ya unos cuantos años los que llevo impartiendo docencia de economía y administración de empresas. Desde mis primeras clases, allá por el año 2010, he ido creando y mejorando los distintos materiales que he ido utilizando.

Sin embargo, con el paso del tiempo, he ido notando que más allá de unas buenas transparencias y una buena colección de ejercicios, problemas y prácticas, lo que sin duda puede ser una diferencia es tener unos buenos apuntes que vayan más allá de las meras enumeraciones y definiciones en las que se suelen convertir las transparencias docentes, y marquen un determinado discurso y permitan profundizar un poco en los conceptos explicados.

Lo ideal sin duda alguna era poder recomendar a mis alumnos un libro de referencia con el que poder seguir la asignatura. Afortunadamente manuales de introducción a la economía y a la administración de empresas hay muchos. Sin embargo, recomendar un libro de 400-500 páginas para un curso introductorio en el que ese contenido se puede ver en 5-8 semanas de clase es, desde mi punto de vista, un pequeño despropósito.

Con estos todos pensamientos en mi cabeza, y toda vez que parecía tener clara la necesidad de tener que fabricarme algo a mi gusto y totalmente adaptado, me faltaba la forma de articularlo. Después de unos años trasteando con `R`, lenguaje de programación que poco a poco he ido aprendiendo y con el que he ido descubriendo como hacer cada día más cosas, llegué hasta el paquete [Bookdown](https://bookdown.org/). Más o menos, y de una forma muy breve, es un paquete que permite crear una estructura de libro utilizando el lenguaje *Markdown*. ¿Ventajas que le veo? Tener actualizado y online (y por tanto disponible para mis alumnos) este compendio de apuntes sin tener que preocuparme demasiado de formatos ni estructuras.

Espero poder decir dentro de un par de años que este experimento ha fraguado correctamente, y que quienes lo estáis leyendo, podéis tener aquí algo así como un que os sirva para el estudio y nos permita dedicar el tiempo de clase a interiorizar los conceptos más que a aprender sobre ellos.

Sea como fuera, aquí está este documento.

## ¿Por qué leer este libro? {-}

Se me ocurre una razón fundamental: soy tu profesor y te lo he recomendado. Si es así, bueno, supongo que lo mejor que puedes hacer es hacerme caso y usar este documento como base para tu estudio y seguir la asignatura.

Puede sin embargo que por otra razón del destino hayas acabado aquí. En ese caso, supongo que habrá algún aspecto del libro que pueda serte de ayuda. Sinceramente, espero que así sea.

## Estructura del libro {-}

El documento está dividido en tres grandes bloques, los mismos en los que suele estar dividida la asignatura. Un primer bloque que aborda el entorno económico de la empresa, donde se verá el funcionamiento básico de la economía, tanto desde la vertiente de la microeconomía (oferta, demanda, mercados), como de la macroeconomía (mercados agregados y políticas), y los entornos genérico y específico. El segundo bloque se introduce en la administración de la empresa: planificación, organización y gestión de los recursos humanos. Además, se dedicará atención a la contabilidad, financiación e inversión en la empresa. Por último, el tercer y último bloque se centra en toda la dirección de la producción y operaciones de la empresa.

Casi todos los contenidos tienen un carácter básico e introductorio, con una visión bastante aplicada a la ingeniería, y están enfocados principalmente a una asignatura general de economía y administración de empresas de nivel de grado. Sin embargo, en algunas secciones aparecerán contenidos con un mayor nivel de detalle, más avanzados y con un mayor grado de aplicación, que están pensados para una asignatura de nivel de máster.

## Lecturas recomendadas {-}

Lo que tienes entre manos (o en la pantalla de tu ordenador, en todo caso delante de los ojos) es una versión muy previa de lo que algún día serán unos buenos apuntes. De momento es un compendio de las secciones más relevantes que he encontrado en alguno de los manuales de economía y empresa que han pasado por mis manos y más me han gustado y que paso a enumerar. Para ampliar cualquiera de los contenidos, no tienes más que recurrir a ellos, pues cualquiera de estos libros contiene mucho mayor detalle en los distintos temas abordados, y que de nuevo al estar estos apuntes enfocados a una asignatura de carácter introductorio, son vistos sin profundidad aquí.

* Juan Manuel Blanco. "Economía: teoría y práctica". McGraw Hill España. 5ª edición.
* Gregor N. Mankiw. "Principios de economía". Cengage Learning España. 7ª edición.
* Michael Parkin. "Economía". Pearson Education. 12ª edición.
* Eduardo Bueno Campos. "Curso básico de economía de la empresa. Un enfoque de organización". Pirámide. 4ª edición.
* José Moyano Fuentes. "Adminsitración de empresas. Un enfoque teórico-práctico". Pearson Education.

## Agradecimientos {-}

Es de rigor aquí también agradecer a los alumnos que han formado parte de este proceso, porque gracias a los comentarios e interés de algunos de ellos, algunos apartados han ganado en contenidos, calidad y ejemplos.

Voy a permitir el destacar algunos de ellos, que sin duda han colaborado y ayudado más a la elaboración del documento:

* David Fernández Díaz (Curso 2018/2019, Grado en Ingeniería de los Recursos Energéticos)

Si has llegado leyendo hasta aquí y detectas en el documento algún error, así como tienes cualquier sugerencia o cambio que crees puede mejorar estos apuntes, no dudes en ponerte en contacto conmigo porque sin duda agradeceré tu interés.
