# El dinero

## ¿Qué es el dinero?

Definimos dinero como todo activo o bien que es generalmente aceptado como medio de pago por los agentes económicos para sus intercambios.

Es posible admitir una segunda definición: "conjunto de activos que se encuentras dentro de una economía y que las personas usan regularmente para intercambiar bienes y servicios".

Para comprender mejor estas definiciones, puede ser una buena idea ver cómo surge el dinero y cuáles son sus principales funciones y características.

## Historia del dinero

Retrocedamos en el tiempo, hasta el neolítico (1900 años a.C.). En aquella época aparecen la agricultura y la ganadería, y con su desarrollo apareció la primera economía de producción y se produjeron los excedentes, es decir, bienes que no necesitan ser consumidos. Esto dio lugar a la posibilidad de alimentar a personas que no necesitaban trabajar la agricultura o la ganadería y podían dedicarse a producir otros productos, como la cerámica o la caza. Con esos excedentes se producía un intercambio de productos. Este intercambio supuso la aparición de la primera forma de comerciar, el trueque, intercambiando directamente bienes y servicios por otros.

El dinero aparece más tarde en la antigüedad remota como una forma de superar los problemas que acarreaba el trueque o intercambio directo de unas mercancías por otras. A medida que las economías se vuelven más complejas y el número de bienes se multiplica, es cada vez más difícil que se verifique la coincidencia de deseos de las dos partes que intervienen en el intercambio si éste se realiza en forma de  trueque. Si sólo existen dos bienes, resulta relativamente fácil que una persona que desea intercambiar el bien 1 (comida) por el bien 2 (vestido) encuentre a otra que desee intercambiar el bien 2 (vestido) por el bien 1 (comida). Pero si hay 100 bienes, resulta difícil que una persona que desea intercambiar el bien 71 (arroz) por el bien 29 (una oveja) encuentre a una persona que desee lo contrario.

Además, existe la dificultad de valorar los bienes que se van a intercambiar. ¿Cuántas ovejas cambio por un kilo de arroz? ¿Y qué sucede si los bienes no son divisibles? ¿Cómo consigo un vestido si yo me dedico a construir casas? Tendría que recibir 500 vestidos cuando yo en realidad sólo necesito uno. ¿Qué hago con los 499 restantes? No sólo es necesaria la coincidencia de necesidades, sino que en el trueque es muy complicado medir exactamente cuánto vale cada bien comparado con el otro.

Solución: todos aceptan cambiar cualquier bien por uno que previamente se ha ﬁjado, por ejemplo, la sal. A este último bien se le denomina dinero mercancía. Ahora se puede cambiar el arroz por sal a una persona para posteriormen- te intercambiar esa cantidad de sal por una oveja a otra persona distinta. La sal se ha convertido, en este ejemplo, en el dinero (de hecho se utilizó en la antigüedad como dinero), ya que es el medio de cambio generalmente aceptado. También es muy probable que todos los precios comiencen a expresarse en unidades de sal (unidad de cuenta). Por otro lado, este método permite que el vendedor del arroz guarde la sal durante ese año y compre la oveja el año  siguiente aplazando así la transacción (sirve como depósito de valor). Como curiosidad, se dice que la palabra «salario» proviene de «sal» dado que en la antigua Roma se realizaban algunos pagos en esta mercancía por la prestación de ciertos servicios. En deﬁnitiva, el dinero mercancía se caracteriza por tener un valor intrínseco o material que coincide con el valor que representa. Además de la sal, otros bienes como el tabaco, la plata y, sobre todo, el oro fueron utilizados como dinero mercancía. Se trataba de bienes que resultasen relativamente escasos (para mantener su valor), no perecederos, de alguna manera divisibles (para facilitar el cambio) y no muy voluminosos. En el caso del oro, y con el ﬁn de garantizar la pureza del material (evitando así a los vendedores tener que comprobar la calidad) las autoridades comenzaron a acuñarlo (distribuirlo en porciones con el sello del monarca o la autoridad feudal) en forma de monedas que expresaban un determinado valor. Como la característica fundamental del dinero mercancía era que su valor material coincidía con el valor que representaba, era posible comprar la misma cantidad de bienes con la moneda de oro que fundiendo la moneda e intercambiando el metal resultante.

A pesar de todo, el oro resultaba un dinero incómodo por el elevado peso del metal. La gente comenzó a percatarse de que podía mantener el oro depositado en alguna institución o persona que garantizase su seguridad y pagar con un papel canjeable por una  determinada  cantidad  de  oro. Estos  depositarios  de  oro  se convertirían con el tiempo en bancos. El receptor del papel podía pagar también con él en lugar de hacerlo efectivo: había nacido el dinero ﬁduciario que se caracteriza porque su valor material (papel) es muy inferior a lo que puede comprar. Pronto las autoridades emiten ese papel (billetes) como una promesa de pago en oro (dinero legal). Todas las personas aceptaban este dinero legal porque sabían que en cualquier momento podían ir al depositario y canjearlo por oro (el oro era el activo que, en aquellos tiempos, respaldaba al dinero legal). Además, las autoridades comenzaron a promulgar leyes y disposiciones que establecían la obligatoriedad de aceptar este dinero como cobro de deudas. Naturalmente que la cantidad de papel moneda que se podía emitir estaba limitada por las disponibilidades de oro.

Tiempo después las autoridades anulan la convertibilidad deldinero legal en oro y comienzan a respaldar el dinero con otros activos distintos (por ejemplo, créditos a entidades, títulos financieros, moneda extranjera, etc.), como se verá más adelante. Si los billetes ya no son canjeables por oro, ¿por qué se siguen aceptando en el intercambio? Por dos motivos. El primero de ellos es que existe  una  obligación  por  ley  de  aceptarlos. El  segundo, y  más importante, por una cuestión de conﬁanza, ya que aceptamos que nos paguen con billetes porque conﬁamos en que nos aceptarán estos mismos billetes en una compra posterior. Así, la palabra fiduciario signiﬁcaría «basado en la conﬁanza». Cuando, en deter- minadas situaciones históricas, los ciudadanos pierden conﬁanza en su moneda, ésta deja de tener alguna de las propiedades que se atribuyen al dinero.

Hoy día las cosas son todavía más complicadas. La mayor parte de las transacciones de cierta entidad no implican intercambio alguno de monedas y billetes (se paga con tarjetas, transferencias bancarias, cheques, etc.) sino meros apuntes en unas cuentas abiertas en entidades de crédito (bancos, cajas de ahorros, etc.). Se llevan a cabo a través del dinero bancario, que está formado por las cuentas o depósitos que los particulares abren en los bancos. Estas cuentas tienen, desde el punto de económico, unas características parecidas a las de las monedas y billetes y pueden servir para realizar pagos. Por ello se consideran también dinero. Hoy día la cantidad total de dinero está formada por dinero legal y dinero bancario.

> TIPOS DE DINERO  
>
>* **Dinero mercancía**: su valor intrínseco coincide con su valor
representativo.  
>* **Dinero fiduciario**: su valor intrínseco es inferior a su valor representativo.  
>   * Dinero legal: monedas y billetes.  
>   * Dinero bancario: cuentas o depósitos en bancos, que
sirven para realizar pagos.

-----------------------------------------------------------

## Funciones y características

El dinero cumple tres funciones básicas:

* Medio de cambio, porque es intercambiable por otros bienes y servicios. Esta función es la principal y anula el trueque. Permite comprar bienes y servicios porque todo el mundo lo acepta como forma de pago. Éste es uno de los motivos por el que las personas mantienen una parte de su riqueza en forma de dinero aunque con ello no obtengan rentabilidad alguna.
* Unidad de cuenta, porque determina el precio de cualquier bien en función de una cantidad de dinero.
* Depósito de valor, debido a que podemos ahorrar dinero para conservar riqueza. Si no se desea consumir hoy lo ganado, es posible mantener el ahorro en forma de dinero aplazando la compra al futuro.

Para poder denominar a un activo dinero, debemos asegurarnos que cumpla sus principales características:

* Aceptabilidad. Una de las razones por las que el dinero funciona en el desempeño de sus funciona es porque es universalmente aceptado por la sociedad y los agentes económicos. Si un bien no es aceptado como dinero, no permite el intercambio de bienes y servicios y por tanto, el funcionamiento del comercio.
* Durabilidad. Si el dinero no fuera duradero y resistente al paso del tiempo, no serviría como depósito de valor y podría además dañarse en los intercambios, perdiendo valor. 
* Transferibilidad. El dinero debe facilitar el intercambio y el comercio. Si no es fácil de usar y transportar, pierde gran utilidad.
* Divisibilidad. Una de las razones por las que surge el dinero es por la necesidad de fraccionar los bienes que intervienen en las transacciones. El dinero debe ser fraccionable para facilitar el intercambio.
* Homogeneidad. Cualquier unidad del dinero debe tener un valor exactamente igual al de las demás.
* Dificultad de producción. Debe de ser difícil de producir y de falsificar.
* Estabilidad. Su valor no debe de estar sujeto a fluctuaciones violentas.

## El dinero como activo

Un activo es cualquier forma de mantener la riqueza. El dinero es, naturalmente, un activo (se puede mantener la riqueza en forma de dinero) pero no es el único. Los activos se dividen en reales y financieros. Los activos reales son aquellos materiales y tangibles: edificios, tierras, maquinaria, medios de transporte, viviendas, etc. Los activos financieros no son tangibles. Son documentos en los que personas o instituciones reconocen una deuda con el poseedor.

Estos documentos constituyen un pasivo para el que lo emitió (debe esa cantidad), pero un activo para el que lo posee (le deben esa cantidad). Ejemplos de activos financieros son: las letras de cambio, las acciones, las obligaciones, los títulos de la deuda pública, las cuentas bancarias o las monedas y billetes. Especial atención merecen estos dos últimos activos.

Los billetes de curso legal constituyen un activo financiero distinto de las cuentas bancarias o depósitos si bien resulta muy sencillo convertir uno en el otro: ingresando en efectivo los billetes en un banco, el individuo está cambiando sus activos de billetes a depósitos. Por el contrario, cuando el individuo se persona en la ventanilla del banco o en el cajero automático para solicitar billetes, está cambiando depósito por billetes. En el lenguaje cotidiano ambos activos se denominan dinero; más adelante se verá que ambos activos son distintos tipos de dinero. Por tanto, el dinero es un activo financiero, se trate éste de billetes o de depósitos. Los billetes representan una deuda de quien los emitió (ya veremos que el Banco Central) con las personas que los poseen. Una cuenta bancaria es un depósito que un particular realiza en un banco. Mediante este instrumento, el banco reconoce la deuda con el particular y le ofrece una serie de servicios relacionados como puede ser la realización de pagos y cobros. El resto de los activos que poseen los individuos pueden convertirse en dinero: por ejemplo, pueden venderse en la bolsa las acciones que se poseen. ¿En qué se diferencian unos activos de otros? Los activos se diferencian entre sí y se clasifican según su liquidez, su riesgo y su rentabilidad.

La liquidez mide la facilidad con la que un activo puede convertirse en dinero sin incurrir en costes o pérdidas. Un inmueble es un activo poco líquido, mientras que los billetes son pura liquidez. La rentabilidad es el interés que ofrece el activo, es decir, lo que se puede ganar por cada euro asignado a ese activo. Existen activos que pueden ser muy rentables (por ejemplo, las acciones), otros muy poco rentables (las cuentas bancarias), mientras que de las monedas y billetes no puede obtenerse rentabilidad.

El riesgo mide la inseguridad de un activo para recuperar lo asignado a él y su rendimiento. Las monedas y billetes tienen bajo riesgo, aunque no nulo. Si se mantiene una buena parte de la riqueza en forma de billetes, se corre el riesgo de sufrir un robo o, tal como vimos en su momento, una pérdida de poder adquisitivo debido a la inflación. Por el contrario, las acciones son activos bastante arriesgados, ya que su valor está sujeto a grandes oscilaciones.

Haciendo una clasificación de los activos, los más líquidos también suelen ser los menos arriesgados y los menos rentables. Por el contrario, los menos líquidos son también los más arriesgados y más rentables. Esta relación directa que existe en los activos financieros entre riesgo y rentabilidad (a mayor riesgo, mayor rentabilidad media) se explica como una consecuencia de la aversión al riesgo de los agentes económicos, que consiste en que a las personas no les gusta el riesgo. Si la rentabilidad de los activos más seguros fuese la misma que la de los activos más arriesgados, nadie mantendría estos últimos. Por tanto, los activos más arriesgados deben ofrecer una rentabilidad media superior (una prima de riesgo) para que las personas los adquieran.

## La creación de dinero

Si todo el dinero utilizado se limitase a monedas y billetes de curso legal, la cantidad de dinero en circulación estaría constituida por lo que se denomina base monetaria. La base monetaria es el conjunto de los pasivos monetarios de un Banco Central (básicamente billetes que han sido emitidos). En el pasado era el oro el activo que respaldaba esta base monetaria. Hoy en día, los billetes están respaldados por otros activos distintos aunque los bancos centrales continúen manteniendo una cierta cantidad de oro.

Sin embargo, hoy en día, el grueso del volumen de transacciones se realiza a través de métodos que no requieren el intercambio de monedas y billetes: se paga con tarjetas, cheques, transferencias bancarias, etc. ¿En qué consisten estas nuevas formas de pago? Se trata, sencillamente, de apuntes contables que realizan unos agentes económicos denominados bancos comerciales privados. Los bancos son empresas que intermedian en los mercados financieros
canalizando fondos de los ahorradores a los particulares y empresas que utilizan dicho ahorro. Las personas realizan depósitos en los bancos (también conocidos como cuentas) y éstos utilizan esos recursos para conceder créditos o préstamos a quien lo solicita.

Un depósito es una anotación (en euros o en otra moneda) que refleja la deuda que el banco contrae con el titular. Se trata, por tanto, de un pasivo para el banco y un activo para el individuo. Los depósitos son activos muy líquidos, ya que resulta sencillo y rápido convertirlos en monedas y billetes: basta con acercarse a la ventanilla del banco o al cajero automático. Una de las características importantes de estos depósitos es que, además de servir para mantener la riqueza, se pueden utilizar para realizar pagos. Las tarjetas, cheques o transferencias no son más que ordenes para modificar el estado de las cuentas o depósitos. Si dos personas tienen la cuenta en el mismo banco, la primera puede pagar a la segunda ordenando una transferencia. El banco realiza la transferencia anotando apuntes que consisten en una reducción (cargo) de la cuantía de la cuenta de la primera persona y un aumento (abono) de la cuantía de la cuenta de la segunda persona. Si cada persona tiene cuenta en un banco distinto el procedimiento es el mismo, la única diferencia es que los bancos compensarán entre sí esta transferencia mediante apuntes en las cuentas que los bancos tienen abiertas, a su vez, en el Banco Central.

Dado que estos depósitos o cuentas sirven para realizar transacciones sin que medie intercambio de monedas y billetes, cumpliendo así una función similar a la de éstos últimos, los depósitos de los particulares en los bancos se consideran dinero. En realidad se trata de otra forma de dinero que, al ser creada por los bancos, se denomina dinero bancario. Los depósitos o dinero bancario son creados por los bancos comerciales en un proceso en el que, a partir del dinero legal (monedas y billetes), se crea una cantidad de dinero que supera, con creces los billetes existentes.

¿Cómo se crea esta nueva cantidad de dinero? Cuando depositamos dinero en nuestra cuenta bancaria, el banco, buscando obtener un beneficio, puede prestar todo ese dinero o parte de él. Imaginemos que tenemos 1.000 euros, y que depositamos en nuestra cuenta del banco 850 euros (el resto nos lo quedamos en el bolsillo para poder gastarlo). De los 850 euros que depositamos, el banco guarda un porcentaje en su caja (para mantener una cierta liquidez por si fuera necesaria, por ejemplo, si vamos a sacar dinero al cajero) y el resto lo presta a otro cliente. Supongamos que presta 800 euros de los 850. Ese nuevo cliente tiene ahora en su poder 800 euros, que sumados a nuestros 1.000 euros implica que la cantidad total de dinero circulando en la economía es de 1.800 euros. Esto no quiere decir que los sujetos seamos más ricos: nosotros seguimos teniendo 1.000 euros, y el otro cliente tiene que satisfacer una deuda. Sin embargo sí que ha aumentado la cantidad de dinero circulando y el banco ha creado  una mayor liquidez.

En teoría este proceso se puede repetir infinitamente. El cliente puede volver a depositar el dinero prestado en otro banco, que a su vez podría volver a prestarlo, etc. En la zona euro, el Banco Central Europeo (BCE) determina como medida de prudencia económica que las entidades depositen un porcentaje de los depósitos de sus clientes en el banco central de cada país en concepto de reservas. Este porcentaje es lo que se denomina coeficiente de caja o coeficiente de reservas. Su finalidad es garantizar la solvencia a corto plazo de los bancos, impidiendo la multiplicación de fondos de un modo descontrolado que pudieran provocar quiebras en el sistema.
