# La política económica

## Objetivos de la política económica

Desde una perspectiva macroeconómica, los gobiernos buscan la consecución de cuatro grandes objetivos:

* Conseguir crecimiento económico. Esto significa ampliar la capacidad Productiva del país para elaborar bienes y servicios. El crecimiento económico se mide en la tasa a la que crece el PIB real.
* Controlar la inflación. Este objetivo busca controlar la tasa de crecimiento de los precios (IPC) para defender el poder adquisitivo de los salarios nominales, de modo de mantener el bienestar de la población.
* Reducir el desempleo. Se trata de lograr pleno empleo de los recursos productivos, especialmente de la mano de obra. Pleno empleo no significa 0% de desempleo, sino que implica aceptar una cierta tasa de desempleo natural. 
* Equilibrio externo o equilibrio en balanza de pagos. El proceso de apertura y globalización de las economías, hace necesario velar por mantener cuentas externas sanas, con saldos moderados y controlables por las autoridades económicas.

Para lograr estos objetivos, las autoridades económicas cuentan con variados instrumentos de política económica. Estos instrumentos permiten determinar el ritmo y rumbo de la actividad económica. Según la bibliografía común, existen dos grandes políticas (la fiscal y la monetaria) y otras que, aunque relevantes, suelen tener un menor peso relativo que las dos anteriores (la política comercial exterior y la política de oferta). Vamos a presentar los elementos que caracterizan a cada una de ellas.

## La política fiscal

Las políticas fiscales son políticas económicas de demanda a través de las cuales el gobierno actúa sobre sus ingresos y gastos para influenciar los niveles de ingresos, producción, y desempleo de la economía. El gobierno puede hacer esto vía impuestos sobre la renta y ayudas al desempleo, o con medidas discrecionales, como los impuestos sobre el gasto y aumentando el gasto público. Aumentando la demanda, las empresas son incentivadas a producir más y por tanto a aumentar la contratación de trabajadores.

El keynesianismo creía que las políticas fiscales son la mejor herramienta para controlar la economía de un país, especialmente para reducir el desempleo cíclico. El monetarismo y otras doctrinas como la nueva macroeconomía clásica y la nueva economía keynesiana consideran estas medidas ineficaces a largo plazo, ya que la demanda no puede aumentar continuamente.

La política fiscal se refiere a las decisiones que determinan los presupuestos generales del Estado, e implican la utilización del gasto público, los impuestos y las transferencias para influir sobre la demanda total de la economía y, así, incidir significativamente sobre el nivel de la producción y renta.

El gasto público incluye las compras del Estado en bienes y servicios, como por ejemplo, la construcción de carreteras, el pago a funcionarios, la compra de ferrocarriles, de aviones, de armamento, etc. Las transferencias del Estado son todos los pagos realizados por el gobierno a familias y empresas que no se corresponden a ninguna actividad productiva, como por ejemplo, las pensiones, las prestaciones de desempleo, las ayudas familiares, etc. Por último, los impuestos son los ingresos corrientes del Estado que proceden de los contribuyentes.

La política fiscal, a través de sus instrumentos, condiciona el consumo y el ahorro privado, y a partir de estas variables, influyen en la producción y en la inversión, primero a corto plazo y más tarde a largo plazo. Por otra parte, la política fiscal incide sobre los precios de los bienes y de los factores de producción y, por tanto, afectan a los incentivos y a la conducta de los individuos.

Una política fiscal expansiva consiste en elevar el gasto total de la economía a través del aumento de las compras del Estado, el aumento de las transferencias o las bajadas de los impuestos sobre la renta. Una política fiscal restrictiva o contractiva es lo contrario: disminución de las compras del Estado, disminución de las transferencias o aumento de los impuestos.

## La política moneraria

Las políticas monetarias son políticas económicas de demanda a través de las cuales el banco central de un país actúa sobre la cantidad de dinero y los tipos de interés para influenciar los niveles de ingresos, producción y desempleo en la economía, siendo el tipo de interés el nexo entre dinero e ingreso. Las principales herramientas usadas por la política monetaria son las operaciones de mercado abierto, los préstamos a los bancos y la modificación de los requisitos de reservas mínimas. Ceteris paribus, un aumento (disminución) en la oferta monetaria o una disminución (aumento) en los tipos de interés tendrá un efecto positivo (negativo) sobre el gasto privado (consumo e inversión). Esto aumentará (disminuirá) finalmente la producción y el empleo. Sin embargo, esto provocará un aumento de los precios, que puede dar lugar a una rápida y creciente inflación.

El monetarismo es la principal doctrina económica que defendía estas políticas. El keynesianismo, la nueva macroeconomía clásica y la nueva economía keynesiana critican estas medidas y no creen en su efectividad ya que ha sido demostrado que un aumento de la oferta monetaria traerá una inflación que contrarrestará los efectos positivos. Como Milton Friedman decía, “la inflación es siempre y en todo lugar un fenómeno monetario”.

En el ámbito del Unión Europea, la política monetaria la realiza el Banco Central Europeo (BCE) y su objetivo principal es tratar de mantener estables los precios. Para ello, el Banco Central Europeo controla la evolución de la cantidad de dinero u oferta monetaria dentro de la Unión Europea (los billetes y monedas es el dinero legal, pero el mayor componente del dinero en las economías modernas es el que se crea dentro del propio sistema bancario a partir de los préstamos, y que sólo figura como apunte bancario). A partir de este control monetario se determinará la cantidad disponible de crédito bancario y, en general, se regulará el funcionamiento del sistema financiero.

Mediante el control de la oferta monetaria el BCE fijará los tipos de interés de referencia en la economía y, con ello, incidirá en la inversión, en el consumo, en la producción, en el nivel general de precios, en los tipos de cambio (y, consiguientemente, en las exportaciones y en las importaciones), en los precios de las acciones y en el precio de las viviendas. De este modo, la política monetaria trata de evitar, o al menos paliar, los inconvenientes derivados de los ciclos económicos.

Un aumento de la cantidad de dinero, con la consiguiente disminución del tipo de interés, es una política monetaria expansiva. Una disminución de la cantidad de dinero con su correspondiente aumento del tipo de interés es una política monetaria restrictiva.

## La política de oferta

El objetivo de las políticas económicas de oferta es aumentar la cantidad ofertada y por tanto el potencial productivo que una economía posee. Este tipo de políticas mueve hacia la derecha la curva de oferta agregada a largo plazo y hacia el exterior la frontera de posibilidades de producción. Pueden ser divididas en políticas que actúan sobre la función de producción y aquellas que actúan sobre los costes laborales.

Las primeras están dirigidas a aumentar los niveles de producción siendo un ejemplo las políticas que incluyen incentivos al progreso tecnológico y el aumento de stock de capital. Por otro lado, las últimas se dirigen directamente a disminuir los costes laborales y de este modo más trabajadores pueden ser contratados. Ejemplos de estas políticas son la reducción de la contribución a la seguridad social, el aumento de subsidios empresariales, la reducción de impuestos indirectos, etc.

Las políticas de oferta han sido defendidas por numerosos economistas incluyendo el premio Nobel Robert Mundell. Ha habido numerosos estudios concernientes a su efectividad, y aunque es cierto que tienen efecto a largo plazo, son las únicas que pueden llevar a un crecimiento económico prolongado. Por otro lado, las corrientes monetarista y keynesiana han sido cuestionadas ya que tanto la política monetaria como la fiscal son únicamente usadas en el corto plazo, siendo inútiles e incluso perjudiciales para la economía en el largo plazo. De hecho, las últimas dos grandes doctrinas, la nueva macroeconomía clásica y la nueva economía keynesiana han demostrado la ineficiencia de las políticas monetarias y fiscales, dejando las políticas de oferta como las únicas verdaderamente eficaces para la economía.

La política de oferta puede aplicarse también como un control sobre las rentas. En este caso, consiste en una política, en principio, de consenso o de pacto entre los grandes grupos sociales de la economía (a saber, Estado, sindicatos como representantes de los trabajadores y empresarios) para moderar las subidas de precios y salarios, y con ello frenar las tensiones inflacionistas y/o los aumentos en la tasa de desempleo. Se pretende controlar la evolución de las rentas de la economía para asegurar y mantener una mayor estabilidad tanto de precios como de empleo. El objetivo de la política de rentas es doble. Por un lado, se intenta fomentar la eficiencia económica mediante la reasignación de los recursos. Y por otro, promover la equidad al redistribuir la renta entre los diferentes agentes económicos.

Cuando el Estado no consigue llegar a este tipo de acuerdos entre los agentes implicados, adoptará una política de rentas de “ordeno y mando”, limitando el precio de determinados productos, congelando o reduciendo los salarios de los funcionarios, estableciendo unos márgenes máximos de subidas de salarios, subvencionando a determinados sectores, o aplicando desgravaciones fiscales, por ejemplo.

## La política exterior

La política comercial trata de influir directamente en la cantidad de bienes y servicios que importa o exporta un país, con el fin de mejorar el saldo comercial con el exterior (es decir, la diferencia entre las exportaciones y las importaciones). Esta política se instrumentaliza a través de los aranceles (impuestos que gravan con una determinada proporción el precio de un bien importado), contingentes (límites físicos o cuantitativos a la cantidad que se puede importar de un determinado bien) y otros mecanismos (subvenciones o ayudas a la exportación, firma de tratados comerciales ventajosos, libre comercio, etc). Otra práctica utilizada por algunos gobiernos es fijar o determinar unilateralmente los tipos de cambio, esto es, estableciendo el precio de la moneda nacional en relación con las monedas extranjeras.

La política comercial intenta propiciar la eficiencia del comercio internacional mediante una mayor competitividad en el exterior, lo cual favorecerá el crecimiento económico, mayores rentas interiores y una mejora del bienestar.

Consideramos la política exterior como aquella parte de la política general formada por el conjunto de decisiones y actuaciones mediante las cuales se definen los objetivos y se utilizan los medios de un Estado para generar, modificar o suspender sus relaciones con otros actores de la sociedad internacional.

A partir de esta definición de la política exterior, podemos señalar sus principales elementos. En primer término su carácter estatal. En efecto, aunque en sentido metafórico se puede hablar de la política exterior de otros actores internacionales (Movimientos Populares; Organizaciones Gubernamentales; etc.),lo cierto es que la política exterior sólo puede predicarse de los Estados ya que son los únicos actores que reúnen los dos requisitos necesarios para poder desarrollarla plenamente: capacidad jurídica reconocida internacionalmente y capacidad política plena, autónoma y eficaz.

En segundo lugar, la política exterior no puede disociarse de la política interior del Estado. Ambas se interfieren mutuamente ya que, en último extremo, ambas no son mas que dos facetas de una misma realidad política, la del Estado, tanto en su dimensión institucional como en su base social. La diferencia entre estas dos esferas de la política del Estado responde, en último extremo, a la diversidad de formas y órganos que participan en la elaboración de una y otra, así como a sus diferentes destinatarios Mientras la política interior se dirige a los individuos y grupos de una misma sociedad estatal, la política exterior está orientada a permitir la vinculación entre Estados.

Además, como toda política, la exterior se articula por una combinación de decisiones y actuaciones de los órganos estatales, de modo principal por parte del Gobierno, sin solución de continuidad. Cuando se quiebra esta ordenada secuencia entre decisiones y actuaciones, podemos afirmar que el Estado carece de una auténtica política exterior. Entonces podemos hablar de que política exterior y acción exterior se confunden al faltar una capacidad decisional autónoma y verdaderamente política.

Por último, la política exterior incluye la determinación de los fines u objetivos que aspira a alcanzar cada Estado, pero debe también incorporar la especificación y utilización de los medios más adecuados para el logro de esos objetivos. Si el país carece de una determinación de sus fines u objetivos, el Estado simplemente actuará en el contexto internacional reaccionando a los acontecimientos coyunturales, sin que pueda hablarse de una política exterior. Análogamente,si carece de los medios necesarios o son manifiestamente insuficientes para alcanzar los fines que se ha trazado, el Estado evidenciará una escasa proyección internacional fruto,en parte,de la impotencia para dar respuesta a los retos que el contexto internacional o las aspiraciones internas le plantean y,de otra,a la débil credibilidad que su política exterior suscitará entre los demás países.

