# (PART) La Administración de Empresas {-}

# La dirección de empresas

La dirección es un área fundamental para el correcto funcionamiento de toda organización que tenga un objetivo. No es necesaria por tanto sólo en las empresas, sino en todo tipo de organización, del tipo que ésta sea, aunque por razones obvias en estos apuntes nos centraremos en el caso de las empresas.

En una empresa se reúnen recursos de características muy diferentes y es función de la dirección, el conseguir que trabajen de forma común para conseguir los objetivos que se planteen. La dirección debe encargarse de asignar y coordinar los recursos existentes, así como estimular su mejora continua y fomentar la generación de nuevos recursos. Este aumento de recursos no se refiere únicamente a los tangibles, generados en forma de inversiones, sino también a los intangibles como es la mejora del conocimiento de los empleados, de sus habilidades, o la consolidación de la imagen de la marca de la empresa en el mercado.

Desde un punto de vista más científico, se plantea la dirección de una empresa como un proceso en el que se realizan varias funciones. Las más clásicas son la planificación, la organización, la dirección de recursos humanos y el control.

Planificar consiste en decidir por adelantado qué vamos a querer hacer en el futuro y con qué medios vamos a dotarnos para realizarlo. Supone tomar una serie de decisiones de forma anticipada pero nos permite determinar qué queremos conseguir, cómo vamos a lograrlo y qué recursos vamos a comprometer en la tarea. Sin embargo, la planificación se debe entender como una ayuda, no como una limitación inamovible. No debe ser un fin mismo, sino una manera de reducir la incertidumbre del futuro.

Organizar se refiere al diseño de la estructura organizativa de la empresa, o lo que es lo mismo, las relaciones entre todos sus miembros. La jerarquía, frente a la opinión de que toda autoridad es mala, es un sistema eficiente de asignación de recursos y surge de la especialización y división del trabajo. La organización jerárquica de una empresa se plasma de una forma sencilla en su organigrama, y en él se reflejan los distintos niveles y puestos organizativos en los que se divide la empresa.

La dirección de recursos humanos integra a los individuos dentro de la estructura organizativa anterior, de tal forma que se consiga la correcta adecuación de los mismos para el logro de los objetivos de la empresa. Para conseguir este objetivo, se debe realizar el reclutamiento, selección, entrenamiento y asignación de las personas a cada uno de los puestos de la empresa.

Por último, el control busca comprobar que el funcionamiento de la empresa se desarrolla dentro de la planificación desarrollada. En caso contrario, el control es el encargado de realizar las correcciones necesarias. Es así pues un complemento a la función de planificación, pues es el control es el encargado de garantizar su cumplimiento. El control consiste en general en medir los resultados obtenidos y compararlos con los esperados para a partir de ahí, identificar diferencias y analizar la forma de corregirlas.
Cada una de estas funciones brevemente desarrolladas aquí son las que se van a explicar en los siguientes temas, así que sirva este pequeño apartado como introducción al bloque de la asignatura en el que nos encontramos.

## Funciones directivas

El trabajo de dirección se puede entender como el conjunto de la serie de actividades o funciones específicas que la integran. Los más básicos de estos conceptos son los siguientes:

1. PREDICCIÓN. Proyección o extrapolación de datos o de información actual para estimar el valor futuro de una magnitud económica o el estado del sistema. También se llama pronóstico.
2.	PREVISIÓN. Conocimiento del valor más probable de una magnitud económica en una fecha futura, a través de la aplicación de un método de análisis de datos.
3.	ESTRATEGIA. Modelo de decisión que revela la misión y objetivos de la organización, así como los planes y políticas para lograrlos, de forma que defina su posición competitiva respecto en qué negocio está o quiere estar.
4.	PLANIFICACIÓN. Estudio y fijación de objetivos y metas, tanto referentes al sistema total como a cada subsistema, aspecto, función y unidad organizativa, incluyendo los cursos de acción que los desarrollan a largo y corto plazo.
5.	POLÍTICA. Respuesta concreta o guía para pensar y decidir respecto de una situación dada o a un problema específico, de forma que permita obtener la solución prevista.
6.	PROGRAMACIÓN. Análisis operativo a corto y medio plazo para llevar a cabo una adecuada asignación de recursos y la aplicación de los consiguientes sistemas de solución de objetivos planificados.
7.	PRESUPUESTACIÓN. Cuantificación financiera y adaptación temporal de los planes y programas elaborados, de forma que permita una adecuada asignación de responsabilidades a las unidades de actuación y facilite el control de los objetivos.
8.	PROCEDIMIENTO. Conjunto de normas, instrucciones y recomendaciones obligatorias que sirven de guía para la acción o para llevar a cabo las actividades que logran los objetivos.
9.	REGLA. Orden o norma para hacer o no hacer alguna acción, de forma que no permita la discrecionalidad.
10.	DECISIÓN. Elección lo más racional posible de las alternativas de un curso de acción para lograr la consecución de los objetivos.
11.	CONTROL. Proceso de observación y medida a través de la comparación sistemática de los objetivos con los resultados obtenidos.

Al mantener relaciones interpersonales, se crea a su alrededor una red de comunicaciones, lo que le permite realizar una serie de labores informativas. Como monitor recoge información, y como difusor y portavoz distribuye información, dentro de la empresa en la primera, fuera en el caso de la segunda función.

Por último, el poseer la información que gestiona en los papeles anteriores, le capacita para tomar decisiones, con lo que cumple con el último bloque de roles, los decisorios. El directivo es empresario, gestor de anomalías, asignador de recursos y negociador.


## La toma de decisiones

Una de las características principales de la administración de la empresa es la de convertir la información en acción. Este paso, es lo que se denomina decisión. La decisión sólo puede producirse cuando el decisor se plantea distintas alternativas sobre las que está perfectamente informado y de las que conoce con precisión cuáles serán sus consecuencias.

La toma de decisiones por tanto se define como la elección racional entre alternativas para lograr la consecución de un objetivo, y es algo intrínseco a la tarea directiva de la empresa. Decidir se asemeja mucho a resolver un problema: cuando algo no marcha bien, cuando algo no funciona, es necesario tomar una decisión para resolver el conflicto.

Al igual que no todos los problemas o conflictos son iguales, todas las soluciones no lo son tampoco. Estas diferencias nos permiten distinguir entre decisiones, según el tipo de problema y la solución que se adopta. Así, podemos separar entre decisiones rutinarias (aquellas con problemas conocidos y que nos permiten programar una respuesta para solucionarlos), adaptativas (aquellas que suponen cambios incrementales sobre la situación precedente; procesos de mejora continua) o innovadoras (aquella mal estructurada, única y novedosa que exige un tratamiento especial).

Según otros autores, esta clasificación de las decisiones se puede realizar también con base a otros criterios, como puede ser el nivel directivo (decisión estratégica global, específica u operativa), la función directiva (decisiones de producción, de comercialización, de financiación, etc.), el horizonte temporal (decisión a largo o a corto plazo) o las características del problema de decisión (decisión programada o no programada).

### El proceso de toma de decisión

El proceso decisorio es algo más que la selección de una alternativa entre varias. Es un conjunto de actividades que deben seguirse en un orden lógico y que abarca desde la identificación del problema hasta la puesta en marcha de acciones que tienen como objetivo resolverlo.

El primer paso es como se ha dicho ya la identificación del problema. No debe bastar con una mera identificación, sino que debe profundizarse y analizar las características del mismo, así como sus síntomas y causas.

El siguiente paso a tomar es la búsqueda de las posibles soluciones. De todas las posibles alternativas de solución que se presenten, será necesario realizar una evaluación. Esta evaluación debe estar diseñada de antemano, por lo que antes de proceder al análisis de las posibles soluciones, será necesario fijar los criterios de evaluación que vamos a utilizar para el análisis de las alternativas.

Decidir consiste en optar entre estas alternativas. Para realizarlo de una forma racional, debemos comparar las alternativas, identificando sus consecuencias, lo que puede esperarse de cada una de ellas y a partir de ahí, elegir la mejor de acuerdo con el criterio de evaluación elegido.

Una vez que hemos elegido la mejor alternativa según nuestros criterios, tan sólo queda su puesta en marcha. Este es el último paso y con el que queda cerrado el proceso decisorio. Toda decisión debe transformarse en una acción.

Es importante ver cómo en cada uno de los pasos que conforman la toma de decisiones, la información es vital, es la materia prima del proceso. Gracias a la información, somos capaces de identificar bien un problema y sus características, buscar alternativas, evaluarlas y llegado el momento, proceder a la puesta en práctica de la solución elegida.

## Los niveles y roles directivos

Las tareas directivas de una empresa tienen tal cierto grado de complejidad que es común que una única persona no pueda ocuparse de todas ellas. El trabajo directivo, como cualquier otro, va experimentando una relativa especialización de tal forma que van apareciendo nuevos puestos no directamente productivos cuya función es la coordinación del resto de personal de la empresa.

El diseño de la estructura de la empresa consiste en ir coordinando el trabajo que se realiza en cada nivel con la creación de una serie de puestos directivos que a su vez, tendrán un control superior. Esto es lo que conforma la estructura piramidal de la organización. Esta jerarquía surge cuando se pone un equipo de trabajo bajo las órdenes de un capataz, que a su vez se encuentra sometido a las instrucciones un directivo de mayor nivel, que estará subordinado a otro de índole superior y así sucesivamente.

En principio, una división sencilla de los niveles directivos los clasifica en tres grupos, en función de sus tareas y responsabilidades: la alta dirección, los directivos de nivel medio y los supervisores de primera línea.

La alta dirección es la encargada de conducir el rumbo de la empresa, fijando sus objetivos y sus líneas estratégicas, estableciendo la marcha general y haciendo que todo funcione de una forma cohesionada. A este nivel afectan multitud de factores, estando entre ellos los medioambientales, lo que hace que se experimente una cierta incertidumbre y que los problemas que surgen sean nuevos y mal comprendidos. Por todo ello, las decisiones que suelen tomarse en este nivel son poco estructuradas y a largo plazo, basándose más en la prueba-error que en otro método, por lo que la reflexión, el buen juicio y la experiencia son básicos en este nivel.

Los directivos de primera línea son aquellos que se encuentran en contacto directo con los trabajadores productivos de la empresa. Ocupan el nivel más bajo de entre todos los que dan órdenes a otros y a diferencia del nivel anterior, las decisiones que se toman en este nivel suelen ser rutinarias y repetitivas, casi siempre con los mismos problemas, por lo que es posible dedicar los recursos al estudio de estos problemas y a la búsqueda de la solución óptima.

Entre ambos niveles, aparecen los directivos de nivel medio, que son los encargados de realizar las tareas de unión entre ambos niveles. Tanto sus superiores como sus subordinados son directivos y su papel básico consiste en transmitir información: en sentido descendente comunican las grandes líneas empresariales fijadas por el nivel superior en forma de objetivos, planes y programas concretos para cada directivo de primera línea, asignando los recursos necesarios; en sentido ascendente coordinan e integran las tareas de los niveles inferiores.

Cada nivel de los anteriores  requiere de diferentes combinaciones de conocimientos y habilidades conceptuales, humanas y tecnológicas, aunque en todos los niveles se necesitará de buenas dosis de destrezas humanas, puesto que en todo trabajo directivo, el trato y la relación con otras personas es algo importante.


