# La dirección de recursos humanos

La función de dirección d e recursos hum anos incluye varias áreas de trabajo que dependen del Departamento de Recursos Humanos e incluyen otras funciones que pueden (y deben) ser ejercidas por cualquier otro miembro de la organización que tenga responsabilidad sobre una o varias personas. Dentro de estas últimas, las dos más importantes son las funciones de motivación y liderazgo.

Hablamos, por tanto, de funciones específicas del Departamento de Recursos Humanos (selección, formación, evaluación) y de funciones genéricas o transversales (motivación y liderazgo).

## La gestión de los recursos humanos

Las organizaciones se enfrentan casi de una forma permanente al problema de incorporar nuevos miembros a sus plantillas. Desde un punto de vista puramente organizativo, es preciso señalar que la finalidad de las estructuras que se conforman en una organización es la homogeneización del comportamiento humano, de forma que cada uno de sus miembros interiorice las normas de comportamiento definidas por la organización.

La selección y formación del personal responden a esta finalidad de homogeneizar las habilidades, conocimientos y valores de los individuos que se van a integrar (selección) o ya pertenecen a la organización (formación). Así, se puede entender que en los procesos selectivos de personal, algunas empresas no tengan en cuenta los méritos objetivos de los candidatos sino que valoren más ciertas cualidades de carácter subjetivo que encajen mejor en el perfil del personal de la empresa.

### Selección

La selección de personal es el proceso por el cual se determinan aquellos candidatos que cumplen de un modo más adecuado los requisitos de trabajo para el que están siendo considerados. La finalidad de la selección es el intentar predecir el futuro comportamiento de los miembros seleccionados para un determinado puesto de trabajo. Para conseguirlo, es necesario analizar la adecuación entre cada uno de los candidatos y el puesto de trabajo, así como pronosticar su futuro rendimiento.

Los métodos de selección ayudan a conocer si las habilidades, conocimientos y experiencia de los candidatos son idóneos para el puesto al que se presenta como candidato. Los más relevantes y utilizados de estos métodos son las entrevistas, las pruebas escritas y las pruebas de simulación.

1. ENTREVISTA. La entrevista suele ser la prueba que se utiliza con mayor frecuencia en los procesos de selección de personal y además suele ser un factor decisivo. Un candidato que se desenvuelve de una manera pobre en una entrevista por lo general es eliminado del proceso selectivo, y al revés, una persona que causa muy buena impresión en la entrevista, suele ser seleccionada aunque no sea el mejor candidato. Las entrevistas deben estar perfectamente estructuradas, con una serie estándar de preguntas, ya que así se facilita la valoración homogénea de los candidatos. Las entrevistas son más valiosas para evaluar la inteligencia, nivel de motivación y habilidades interpersonales del solicitante.
2. PRUEBA ESCRITA. Las pruebas típicas por escrito son exámenes de inteligencia, aptitud, habilidad, interés e integridad. Se ha demostrado que las pruebas de habilidad intelectual, habilidad espacial y mecánica, precisión perceptual y habilidad motriz son predictores moderadamente válidos para muchos puestos operativos semicalificados y que no requieren calificación en las organizaciones industriales. Las pruebas de inteligencia son predictores razonablemente buenos para los puestos de supervisión.
3. PRUEBA DE SIMULACIÓN DE DESEMPEÑO. Es posiblemente una de las pruebas que mejor permiten determinar si un candidato puede desempeñar el trabajo para el que se le está seleccionando con éxito. Las dos pruebas de simulación mejor conocidas son el muestreo del trabajo y los centros de evaluación. El muestreo de trabajo es una reproducción en miniatura del puesto de trabajo en el que los candidatos demuestran que tienen las cualidades necesarias para desarrollar realmente las tareas del puesto. En los centros de evaluación se aplica una serie de pruebas de simulación del desempeño y están específicamente diseñadas para evaluar el potencial de administración.

### Formación

El proceso de formación es simplemente una continuación del proceso de selección que se lleva a cabo en la empresa u organización. Se busca que la ejecución de las tareas por parte de los miembros conduzca a la consecución de los objetivos organizativos.

La formación es necesaria en las organizaciones por dos cuestiones. Por un lado, es prácticamente imposible conseguir la perfecta adecuación en los procesos de selección entre los candidatos y los puestos a cubrir, por lo que el nuevo personal necesitará de un periodo de aprendizaje y adaptación al funcionamiento concreto de la empresa, su cultura y sus procedimientos. Por otro lado, el hecho de que el mundo se encuentre en un continuo desarrollo (en múltiples áreas: tecnología, conocimiento, aplicaciones, etc.) implica la necesidad de aplicar una formación continua al personal de la empresa.

Las habilidades del personal de la organización se pueden dividir en tres categorías: técnicas, interpersonales y de solución de problemas. Estas habilidades deben ser mejoradas tanto en el puesto de trabajo como fuera de él, para lo cual existen diferentes metodologías:

1. FORMACIÓN EN EL PUESTO DE TRABAJO. Los métodos más populares de capacitación en el puesto incluyen la rotación de puestos y las asignaciones de suplente. La rotación en el puesto implica transferencias laterales que permiten que los empleados trabajen en diferentes puestos. Los empleados llegan a aprender una gran variedad de puestos y obtienen mayores elementos de juicio de la interdependencia existente entre los puestos y una mejor perspectiva de las actividades organizacionales. En las asignaciones de suplente, el sustituto trabaja bajo la observación de un trabajador experimentado, que actúa como el modelo que el sustituto trata de emular.
2. FORMACIÓN FUERA DEL PUESTO DE TRABAJO. Existen diversos métodos de capacitación fuera del puesto que los administradores tal vez deseen poner a disposición de los empleados. Los más populares son las conferencias en salones de clase, videos y ejercicios de simulación.

Los individuos, durante su desempeño laboral, desarrollan cinco patrones específicos. Cada uno de estos patrones, que aúnan talentos y habilidades, motivos y necesidades, actitudes y valores, estabilizan la carrera laboral de una persona. Estos patrones se recogen en la siguiente tabla:

PATRONES | 
-------- | --------
COMPETENCIA TÉCNICA/FUNCIONAL | Acentúa el contenido real del trabajo de una persona.
COMPETENCIA ADMINISTRATIVA | Insiste en la ocupación y el ejercicio de la responsabilidad de administrador.
SEGURIDAD | Estabilidad en el trabajo.
AUTONOMÍA | Mantenimiento de su independencia y libertad.
CREATIVIDAD | Deseo ferviente de crear algo que es totalmente de su hechura.

Ejemplificando lo anterior, podríamos decir que dentro de la competencia técnica, una persona que desempeñe un puesto poco o nada relacionado con sus estudios, puede encontrar en este trabajo un desafío que contradice su concepto de ocupación básico. Un empleado con una con una elevada competencia administrativa busca situaciones en la que puede ejercer su capacidad de análisis y sus habilidades interpersonales para ejercer poder. Los individuos con un alto desarrollo de la seguridad, son capaces de renunciar a un trabajo que suponga una gran oportunidad y reto, a cambio de mantener una estabilidad organizacional, un buen contrato con un buen plan de jubilación. La competencia de autonomía hace que los empleados traten de minimizar las restricciones organizacionales, prefiriendo trabajar en grupos pequeños que en grandes corporaciones. Por último, las personas que poseen una alta creatividad necesitan comenzar proyectos nuevos, realizar investigaciones, ser partícipes principales de nuevos equipos para afianzar su autoestima.

## La comunicación en las organizaciones

Como se ha visto en los apartados anteriores, tanto la motivación como el liderazgo se transforman al final en un problema de comunicación, por lo que es relevante proceder al estudio de la transmisión de la información en el interior de una organización.

Se puede definir la comunicación como el proceso por el cual una fuente de información tiende a obrar sobre un receptor de forma que provoque en éste último la aparición de actos o sentimientos. Al definir la comunicación como un proceso de transmisión, la cuestión no reside sólo en si debe existir o no comunicación, sino también en analizar la forma en la que se lleva a cabo el proceso para que lleve a cabo su misión.

Los elementos básicos de los que consta todo proceso de comunicación son lenguaje, reglas, relación entre emisor y receptor, actitud recíproca y una finalidad en la comunicación. Además, para que se pueda realizar la comunicación debe existir un mensaje y un canal de comunicación que permita la transmisión.

La comunicación así definida desempeña cuatro funciones principales dentro de una organización: control, motivación, expresión emocional e información.

1. CONTROLAR. La comunicación actúa para controlar el comportamiento de los miembros en varias formas. Las organizaciones tienen jerarquías de autoridad y lineamientos formales que requieren el cumplimiento por parte de los empleados.
2. MOTIVAR. La comunicación fomenta la motivación al aclarar a los empleados lo que se debe hacer, lo bien que lo están desarrollando y lo que se puede hacer para mejorar el desempeño si éste se encuentra por debajo del promedio. La formación de metas específicas, la retroalimentación sobre el avance hacia las metas y el reforzamiento del comportamiento deseado: todo esto estimula la motivación y requiere de la comunicación.
3. EXPRESIÓN EMOCIONAL. Un grupo de trabajo es una fuente básica de interacción social. La comunicación que tiene lugar dentro del grupo es un mecanismo fundamental por el cual los miembros muestran sus frustraciones y sus sentimientos de satisfacción. Por tanto, la comunicación proporciona un escape para la expresión emocional de sentimientos y para la satisfacción de necesidades sociales.
4. INFORMAR. Se relaciona con el papel de la comunicación para facilitar la toma de decisiones. Proporciona la información que los individuos y grupos necesitan para tomar decisiones, al transmitir los datos para identificar y evaluar opciones alternativas. 

En el seno de las organizaciones, la información puede fluir vertical (en dirección ascendente o descendente) o lateralmente.

1. DESCENDENTE. Es aquella comunicación que fluye desde un nivel superior en la jerarquía organizativa hacia un nivel subordinado de la misma. Este tipo de comunicación suele transmitir metas de trabajo, instrucciones, políticas, procedimientos, etc. Uno de los principales problemas que pueden aparecer en este tipo de comunicación es el de las interferencias en el canal, principalmente por la existencia de una cadena de mando excesivamente larga.
2. ASCENDENTE. Es la transmisión de información desde un nivel inferior o subordinado hacia un nivel superior de la organización. Se utiliza como método de retroalimentación de los niveles superiores, para informarles del progreso hacia la consecución de las metas e informar de problemas existentes. Este tipo de comunicación permite a los administradores mantenerse actualizados sobre la forma como piensan sus subordinados.
3. LATERAL. Este tipo de comunicación tiene lugar entre miembros de un mismo grupo o nivel jerárquico. Las comunicaciones laterales (horizontales o cruzadas) son necesarias para ahorrar tiempo y facilitar la coordinación dentro de la organización. Con frecuencia se crean informalmente para hacer circuitos más cortos que los de la jerarquía vertical y facilitar la acción.

FACTORES QUE FAVORECEN UNA COMUNICACIÓN EFICAZ | 
--- | ---
ADMINISTRADORES COMPROMETIDOS CON LA IMPORTANCIA DE LA COMUNICACIÓN | 
ADMINISTRADORES QUE SINTONIZAN LAS ACCIONES CON LAS PALABRAS | 
EXISTENCIA DE COMPROMISO CON LA COMUNICACIÓN EN AMBOS SENTIDOS | 
PONER ÉNFASIS EN LA COMUNICACIÓN CARA A CARA | 
COMPARTIR LA RESPONSABILIDAD POR LAS COMUNICACIONES CON LOS EMPLEADOS | 
SABER MANEJAR LAS MALAS NOTICIAS | 
ELABORAR UN MENSAJE MODELADO PARA LAS PERSONAS QUE LO VAN A RECIBIR | 
TRATAR LA COMUNICACIÓN COMO PROCESO CONTINUO | 


## La motivación y el liderazgo

El problema de la motivación humana supone el estudio del liderazgo en la empresa en todos los niveles, tanto formal como informal, así como desarrollo de procesos de comunicación adecuados que permitan la necesaria transmisión de información entre las diferentes partes de la organización.

La motivación humana intenta explicar por qué las personas se comportan de una determinada manera. Todo comportamiento humano está motivado de una u otra manera, y la motivación es la tensión que lleva a un individuo a comportarse de tal forma que satisfaga una o más de sus necesidades (Chiavenato, 1987).

Según Maslow (1943 y 1954), la motivación de las personas depende de cinco tipos de necesidades: fisiológicas, de seguridad, de afecto, de estima y de autorrealización. Estas necesidades se organizan según una cierta jerarquía, o lo que es lo mismo, un nivel más alto de necesidad se convierte en una fuente activa de motivación sólo cuando las necesidades que ocupan los niveles inferiores han sido satisfechas.

Según Herzberg (1966 y 1971) se distinguen dos grandes subsistemas de factores que influyen activamente en la motivación. Por un lado, tenemos una serie de condiciones que producen insatisfacción entre los individuos si no se satisfacen en el puesto de trabajo. Tenemos entre estos factores, llamados insatisfactores, el salario, la seguridad en el puesto de trabajo, las condiciones de trabajo, el estatus, los procedimientos en la empresa, la calidad de la supervisión técnica y la calidad de las relaciones interpersonales. Por otro lado, aparecen los condicionantes que producen satisfacción, y que se llaman motivadores. Entre estos segundos aparecen el logro, el reconocimiento, el propio trabajo, la responsabilidad, el progreso y el crecimiento.

McGregor (1975) plantea dos teorías extremas y completamente diferentes que incluyen sistemas de estudio de la motivación en el trabajo. Son las que se denominan “Teoría X” y “Teoría Y”. En la primera de ellas se plantea la imposibilidad de motivar positivamente a un trabajador, mientras que en la “Teoría Y”, McGregor parte de la hipótesis de que es posible diseñar un sistema que consiga la motivación individual en las organizaciones.

TEORÍA X | TEORÍA Y
-------- | --------
Los seres humanos evitan el trabajo siempre que sea posible, porque lo consideran algo impuesto. | El trabajo puede ser fuente de satisfacción o de sufrimiento, en función de condiciones que se pueden controlar.
Las organizaciones deben controlar y amenazar con castigos a los participantes para conseguir su esfuerzo en busca de los objetivos comunes. | A parte del control externo y las amenazas, el ser humano puede autocontrolarse y autodirigirse como modo de estímulo.
El ser humano prefiere ser dirigido a dirigir. | Las recompensas deben estar directamente asociadas a los compromisos asumidos.
El individuo trata de eludir responsabilidades siempre que le sea posible. | Las personas pueden aprender a asumir responsabilidades.
El ser humano tiene poca ambición. | El ser humano tiene capacidad de imaginación, creatividad e ingenio.
Las personas se preocupan principalmente de su propia seguridad. | Se puede conseguir una mayor utilización del potencial intelectual, generalmente infrautilizado.

Complementando las teorías de McGregor, Ouchi (1982) propuso la “Teoría Z”, en la que plantea una situación de partida sobre la cual construir una organización que consiga la motivación de sus miembros.


TEORÍA Z | 
-------- | -
Coordinación de objetivos: confianza y coordinación entre los objetivos de los grupos, los individuos y los de la organización. | 
Lealtad: fidelidad y nobleza entre los participantes, y de forma recíproca entre empleados y dirección. | 
Equidad: el equilibrio como manifestación de la justicia. | 
Sentido de la realidad: reconocimiento de los errores para corregirlos, y de los aciertos para potenciarlos. | 
Sutileza: supone el intento de llegar a lo más profundo de la realidad. | 
Espíritu de equipo: el individuo se siente parte de un grupo y es capaz de multiplicar su esfuerzo y actividad. | 

Las tendencias actuales contemplan el tema de la motivación como uno de los problemas fundamentales de toda organización y de su gestión, reconociendo que estos problemas surgen porque los individuos tienen sus propios intereses personales que muy pocas veces están en consonancia con los intereses del resto de individuos, de los grupos a los que pertenecen o del conjunto de la sociedad.

Partiendo de la hipótesis de que el individuo hará aquello que resulte de su propio interés, el problema de la motivación se transforma en arreglar los problemas y las acciones cotidianas de tal forma que las acciones individuales tengan en consideración, no sólo cómo afecta la decisión a quien la toma, sino también como afecta al resto de individuos (Milgrom y Roberts, 1993).

## El liderazgo y el poder

Se puede partir de la definición de que el liderazgo es la habilidad de influir en un grupo para que alcance las metas, lo que a su vez puede verse como una fuente de poder. Por ello vamos a estudiar brevemente el concepto de poder y cómo puede influir a las organizaciones y sus administradores.

### El poder

El poder es la capacidad para afectar en el comportamiento de otros individuos de una manera predeterminada. En su sentido más general significa la capacidad que posee un individuo (u organización) para producir la ocurrencia de algo. Quien tiene poder puede amenazar con el uso de la fuerza o con sanciones. La propia amenaza ya es poder.
French y Raven (1983) diferencian entre cinco fuentes distintas de poder, que se recogen en la tabla siguiente:

FUENTE DE PODER | 
--- | ---
Poder de recompensa | Poder cuya base está en la propia habilidad para recompensar
Poder de coerción | Poder basado en la habilidad para imponer castigos
Poder legítimo | Poder en el que el receptor reconocer al portador del poder el derecho de influenciarle y acepta la obligación de acatarle
Poder de referencia | Poder en el que el receptor se identifica con el portador del poder y trata de actuar como él
Poder experto | Poder basado en los conocimientos especiales que el receptor del poder atribuye al portador del mismo

La principal fuente de poder en las organizaciones es el manejo de la incertidumbre en la resolución de problemas. Los puntos de la organización que reciben información del exterior y transmiten conclusiones al interior son denominados puntos de absorción de incertidumbre, y el manejo de estos puntos es la mayor fuente de poder en las organizaciones. Así pues, se puede afirmar que el poder de una organización es en el fondo un problema de información. La información como fuente de poder.

### ¿Líderes o administradores?
Ya hemos definido antes el liderazgo como la habilidad para influir en un grupo. Y atendiendo a esta definición podemos plantearnos si no estamos ante el mismo concepto que el de administración. La mayoría de los expertos argumentan que el liderazgo y la administración son diferentes.

Difieren en su motivación, historia personal y la forma cómo piensan y actúan. Los administradores tienden a adoptar actitudes impersonales hacia las metas, mientras que los líderes adoptan una actitud personal y activa hacia ellas. Los administradores tienden a considerar el trabajo como un proceso integrador que implica alguna combinación de personas e ideas que interactúan para establecer estrategias y tomar decisiones. Los administradores prefieren trabajar con la gente; los líderes, que se preocupan más bien de las ideas, se relacionan con la gente de manera más intuitiva y solidaria.

La administración se ocupa del manejo de la complejidad, de proporcionar un determinado orden y consistencia, formulando planes formales, diseñando estructuras y controlando los resultados. Sin embargo, el liderazgo trata de llevar a cabo el cambio, estableciendo la dirección a tomar y organizando a la gente para que lleve a cabo ese proceso.

Puesto que el cargo de administrador confiere un cierto grado de autoridad, podríamos llegar a pensar que todo administrador es un líder, pero no es así. Y tampoco, todo líder es un administrador. El que una organización dé a sus administradores ciertos derechos no proporciona la seguridad necesaria para poder dirigir con eficacia.
